CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    parent_id INT,
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);

INSERT INTO categories (name, parent_id) VALUES
    ('Language learning', NULL),
    ('IT Sphere', NULL),
    ('Science and education', NULL),
    ('Art and creativity', NULL),
    ('Sports and fitness', NULL),
    ('Personality development', NULL),
    ('Health and harmony', NULL),
    ('English', 1),
    ('Arabic', 1),
    ('French', 1),
    ('Spanish', 1),
    ('Chinese', 1),
    ('Hindi', 1),
    ('German', 1),
    ('Other languages', 1),
    ('AI/ML develpment', 2),
    ('Web/App developent', 2),
    ('System development', 2),
    ('Cybersecurity', 2),
    ('Data science/Big data', 2),
    ('VR/AR', 2),
    ('Blockchain', 2),
    ('Mathematics', 3),
    ('Physiscs', 3),
    ('Chemistry', 3),
    ('Biology', 3),
    ('Geography', 3),
    ('Other subjects', 3),
    ('Drawing', 4),
    ('Music', 4),
    ('Dancing', 4),
    ('Acting', 4),
    ('Fitness traingin', 5),
    ('Yoga', 5),
    ('Martial arts', 5),
    ('Swimming', 5),
    ('Psychology', 6),
    ('Career cnsulting', 6),
    ('Soft skills', 6),
    ('Dietics and nutrition', 7),
    ('Health lifestyle', 7);
