"""New Migration

Revision ID: 670fa1e6fb9c
Revises: cb766ceb3667
Create Date: 2023-09-09 20:48:10.044042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670fa1e6fb9c'
down_revision: Union[str, None] = 'cb766ceb3667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
