package configs

import (
	"fmt"
	"log"
	"os"
)

var DATABASE_URL = os.Getenv("DATABASE_URL")
var SERVER_HOSTNAME = os.Getenv("SERVER_HOSTNAME")
var DOCS_HOSTNAME = os.Getenv("DOCS_HOSTNAME")
var GOOGLE_CALLBACK_DOMAIN = os.Getenv("GOOGLE_CALLBACK_DOMAIN")
var GOOGLE_OAUTH_CLIENT_ID = os.Getenv("GOOGLE_OAUTH_CLIENT_ID")
var GOOGLE_OAUTH_CLIENT_SECRET = os.Getenv("GOOGLE_OAUTH_CLIENT_SECRET")
var GOOGLE_OAUTH_REDIRECT_PAGE = os.Getenv("GOOGLE_OAUTH_REDIRECT_PAGE")
var GOOGLE_EMAIL_ADDRESS = os.Getenv("GOOGLE_EMAIL_ADDRESS")
var GOOGLE_EMAIL_SECRET = os.Getenv("GOOGLE_EMAIL_SECRET")
var FACEBOOK_APP_ID = os.Getenv("FACEBOOK_APP_ID")
var FACEBOOK_APP_SECRET = os.Getenv("FACEBOOK_APP_SECRET")
var FACEBOOK_CALLBACK_DOMAIN = os.Getenv("FACEBOOK_CALLBACK_DOMAIN")
var FACEBOOK_OAUTH_REDIRECT_PAGE = os.Getenv("FACEBOOK_OAUTH_REDIRECT_PAGE")
var PASSWORD_RESET_REDIRECT_PAGE = os.Getenv("PASSWORD_RESET_REDIRECT_PAGE")

func LoadAndCheck() {
	if DATABASE_URL == "" {
		log.Fatal("DATABASE_URL not set")
	}

	if SERVER_HOSTNAME == "" {
		log.Fatal("SERVER_HOSTNAME not set")
	}

	if DOCS_HOSTNAME == "" {
		log.Fatal("DOCS_HOSTNAMENAME not set")
	}

	if GOOGLE_CALLBACK_DOMAIN == "" {
		log.Fatal("GOOGLE_CALLBACK_DOMAIN not set")
	}

	if GOOGLE_OAUTH_CLIENT_ID == "" {
		log.Fatal("GOOGLE_OAUTH_CLIENT_ID not set")
	}

	if GOOGLE_OAUTH_CLIENT_SECRET == "" {
		log.Fatal("GOOGLE_OAUTH_CLIENT_SECRET not set")
	}

	if GOOGLE_OAUTH_REDIRECT_PAGE == "" {
		log.Fatal("GOOGLE_OAUTH_REDIRECT_PAGE not set")
	}

	if GOOGLE_EMAIL_ADDRESS == "" {
		log.Fatal("GOOGLE_EMAIL_ADDRESS not set")
	}

	if GOOGLE_EMAIL_SECRET == "" {
		log.Fatal("GOOGLE_EMAIL_SECRET not set")
	}

	if FACEBOOK_APP_ID == "" {
        log.Fatal("FACEBOOK_APP_ID not set")
    }

	if FACEBOOK_APP_SECRET == "" {
        log.Fatal("FACEBOOK_APP_SECRET not set")
    }

	if FACEBOOK_CALLBACK_DOMAIN == "" {
        log.Fatal("FACEBOOK_CALLBACK_DOMAIN not set")
    }

	if FACEBOOK_OAUTH_REDIRECT_PAGE == "" {
        log.Fatal("FACEBOOK_OAUTH_REDIRECT_PAGE not set")
    }

	if PASSWORD_RESET_REDIRECT_PAGE == "" {
		log.Fatal("PASSWORD_RESET_REDIRECT_PAGE not set")
	}

	fmt.Println("1", "DATABASE_URL", "=", DATABASE_URL)
	fmt.Println("2", "SERVER_HOSTNAME", "=", SERVER_HOSTNAME)
	fmt.Println("3", "DOCS_HOSTNAME", "=", DOCS_HOSTNAME)
	fmt.Println("4", "GOOGLE_CALLBACK_DOMAIN", "=", GOOGLE_CALLBACK_DOMAIN)
	fmt.Println("5", "GOOGLE_OAUTH_CLIENT_ID", "=", GOOGLE_OAUTH_CLIENT_ID)
	fmt.Println("6", "GOOGLE_OAUTH_CLIENT_SECRET", "=", GOOGLE_OAUTH_CLIENT_SECRET)
	fmt.Println("7", "GOOGLE_OAUTH_REDIRECT_PAGE", "=", GOOGLE_OAUTH_REDIRECT_PAGE)
	fmt.Println("8", "GOOGLE_EMAIL_ADDRESS", "=", GOOGLE_EMAIL_ADDRESS)
	fmt.Println("9", "GOOGLE_EMAIL_SECRET", "=", GOOGLE_EMAIL_SECRET)
	fmt.Println("10", "FACEBOOK_APP_ID", "=", FACEBOOK_APP_ID)
	fmt.Println("11", "FACEBOOK_APP_SECRET", "=", FACEBOOK_APP_SECRET)
	fmt.Println("12", "FACEBOOK_CALLBACK_DOMAIN", "=", FACEBOOK_CALLBACK_DOMAIN)
	fmt.Println("13", "FACEBOOK_OAUTH_REDIRECT_PAGE", "=", FACEBOOK_OAUTH_REDIRECT_PAGE)
	fmt.Println("14", "PASSWORD_RESET_REDIRECT_PAGE", "=", PASSWORD_RESET_REDIRECT_PAGE)
}
