basePath: /
host: localhost:8000
info:
  contact:
    email: '[TODO]'
    name: API Support
    url: '[TODO]'
  description: Marketplace to connect students and teachers
  license:
    name: '[TODO]'
    url: '[TODO]'
  termsOfService: '[TODO]'
  title: Study marketplace API
  version: 0.0.1
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
schemes:
- http
swagger: "2.0"
